[package]
name = "cuda-lib"
version = "0.1.0"
edition = "2021"
description = "cuda-lib is a about libcuda.so project"

[lib]
name="cuda"
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
